before_script:
  - apt-get update
  - apt install -y make git
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - build
  - unit_tests
  - integration_tests
  - package

stockmono_build:
  image: ubuntu:20.04
  stage: build
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y mono-complete mono-xbuild fsharp
    - mono --version

    - ./configure.sh
    - make

newmono_build:
  image: ubuntu:20.04
  stage: build
  artifacts:
    paths:
      - bin/*.zip
    expire_in: 50days
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    - ./configure.sh
    - make
